### ISSUE TITLE
t/collector-http.t may fail

### ISSUE THREAD

**Issue by eserte** [jhthorsen/mojo-netdata#1]
t/collector-http.t fails under some circumstances like in this fail report: http://www.cpantesters.org/cpan/report/cd8b21c2-807c-11ec-be14-c8621f24ea8f

It seems that this happens if "none.localhost" actually resolves to something and there's a HTTP server running on port 80.
(In this special case it looks like my hoster's DNS resolves *.localhost to 127.0.0.1, and there's a web server running on one of the smoker systems)

**Comment by jhthorsen** [comment]
Thank you for the details! I couldn't understand how it would fail. I'll fix it later today 👍
